# Linear Algebra

In [2]:
import numpy as np

# Matrix

The arrangement of data in the form rows and columns enclosed in a square brackets is called Matrix.

### Creating Matrices

In [3]:
# method -I
A = np.mat([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [4]:
# Method-II
B = np.array([[1,2,4],[3,4,5]])
print(B)

[[1 2 4]
 [3 4 5]]


### order of MAtrix

We can use numpy.shape() function to get the dimension or order of a matrix. It returns a tuple containing the number of rows (m) and the number of columns (n) of a matrix.

In [5]:
np.shape(B)

(2, 3)

In [6]:
print("order:  row x column:   ",B.shape[0]," x ",B.shape[1])

order:  row x column:    2  x  3


###### No. of Elements in a MAtrix

In [7]:
np.size(B)

6

In [8]:
# Example:
Z = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(Z)
print("\n(rows,columns) :  ",np.shape(Z))
print("No. of elements :  ",np.size(Z))

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

(rows,columns) :   (4, 5)
No. of elements :   20


### Is square matrix or Rectangular Matrix?

        Square Matrix => number of rows = number of columns
    Rectangular Matrix => numbers of rows != number of columns

In [9]:
def check_Type(A):
    (m,n) = np.shape(A)
    if not(m==n):
        print('Rectangular Matrix')
    else:
        print('Square Matrix')
       
    
A= np.array([[1,2],[3,4]])
print(A)
check_Type(A)

[[1 2]
 [3 4]]
Square Matrix


In [10]:
B = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
print(B)
check_Type(B)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]
Rectangular Matrix


### Null Matrix

A matrix in which all entries are zero

In [11]:
n = np.zeros((3,3))
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### is null matrix?

In [16]:
def check_null(A):
    if not np.any(A):
        print('Null Matrix')
    else:
        print('Not null')
        
n = np.zeros((3,3))
print(n)
check_null(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Null Matrix


In [17]:
f = np.array([[1,2,3],[0,0,0],[2,3,4]])
print(f)
check_null(f)

[[1 2 3]
 [0 0 0]
 [2 3 4]]
Not null


### Diagnol Matrix

A square matrix in which all the entries except those on main diagnol are zero

In [18]:
C1 = np.array([[4,0,0],[0,5,0],[0,0,-3]])
C2 = np.diag([4,5,-3])

print('Matrix C1:')
print(C1)
print('\nMatrix C2:')
print(C2)


Matrix C1:
[[ 4  0  0]
 [ 0  5  0]
 [ 0  0 -3]]

Matrix C2:
[[ 4  0  0]
 [ 0  5  0]
 [ 0  0 -3]]


### is Diagnol?

In [19]:
def check_diag(A):
    if np.array_equal(A,np.diag(np.diagonal(A))):
        print('Diagonal Matrix')
    else:
        print('--')

        
print(C1,"\n")
check_diag(C1)

[[ 4  0  0]
 [ 0  5  0]
 [ 0  0 -3]] 

Diagonal Matrix


### Accessing diagnol elements

In [20]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print('\nDiagonal elements of matrix A: ')
print(np.diagonal(A))   # or print(A.diagonal())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements of matrix A: 
[1 5 9]


### Scalar MAtrix

A square matrix in which all the elements in a main diagnol are same and remaining entries are zero

In [21]:
S1 = np.diag([5,5,5])

print('Scalar Matrix S1: ')
print(S1)

Scalar Matrix S1: 
[[5 0 0]
 [0 5 0]
 [0 0 5]]


### Identity MAtrix

A scalar matrix in which all the elements on main diagonal are 1.

In [22]:
I3 = np.identity(3)
I4 = np.eye(4)     # Similar to MATLAB

print('3rd order Identity Matrix')
print(I3)
print('4th order Identity Matrix')
print(I4)

3rd order Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4th order Identity Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
def check_identity(A):
    m = np.shape(A)[0]
    if np.array_equal(A,np.diag(np.diagonal(A))) and \
       (len(np.unique(np.diagonal(A)))==1) and \
        A[0,0]==1:
        print(f'It is Identity Matrix of order {m}')
    else:
        print('Not identity matrix')
            
print(I3)
check_identity(I3)
S1 = np.diag([5,5,5])
print("\n\n",S1)
check_identity(S1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
It is Identity Matrix of order 3


 [[5 0 0]
 [0 5 0]
 [0 0 5]]
Not identity matrix


### Transpose of a Matrix

A matrix that is obtained by interchanging of rows and columns of a given matrix is known as Transpose of that matrix.

##### Methods of Transpose
      i) np.transpose(A)     # First Method
     ii) A.transpose()       # Second Method
    iii) A.T                 # Shortcut Method

In [24]:
C = np.array([[1,2,3,4],[5,6,7,8]])
print(C)
print("\n\t\t Transpose of above matrix: \n")
print(np.transpose(C))

[[1 2 3 4]
 [5 6 7 8]]

		 Transpose of above matrix: 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Symmetric and SKew Symmetric

        Symmetric =>  Transpose of A = A
    Skew Symmetric => Transpose of A = -A

In [25]:
def check_symmetric(A):
    if np.array_equal(A,A.T):
        print('is Symmetric Matrix')
        
    elif np.array_equal(-A,A.T):
        print("is Skew SYmmetric")
    else:
        print('--')

In [26]:
SM = np.array([[2,-5,8],[-5,3,6],[8,6,1]])
print('Matrix : ')
print(SM,"\n")
check_symmetric(SM)

Matrix : 
[[ 2 -5  8]
 [-5  3  6]
 [ 8  6  1]] 

is Symmetric Matrix


In [27]:
A = np.array([[0,-2,11],[2,0,5],[-11,-5,0]])
print('Matrix')
print(A,"\n")
check_symmetric(A)

Matrix
[[  0  -2  11]
 [  2   0   5]
 [-11  -5   0]] 

is Skew SYmmetric


### Addition

In [28]:
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[5,6,7,8],[1,2,3,4]])
print("   MAtrix  A: ")
print(A)

print("\n  Matrix   B: ")
print(B)

print("\n A+B ")
sum = A+B
print(sum)

   MAtrix  A: 
[[1 2 3 4]
 [5 6 7 8]]

  Matrix   B: 
[[5 6 7 8]
 [1 2 3 4]]

 A+B 
[[ 6  8 10 12]
 [ 6  8 10 12]]


### SUbtraction

In [29]:
A = np.array([[5,6,7,8],[13,9,11,12]])
B = np.array([[3,2,1,5],[5,6,7,4]])
print("   MAtrix  A: ")
print(A)

print("\n  Matrix   B: ")
print(B)

print("\n B-A ")
sub = A-B
print(sub)

   MAtrix  A: 
[[ 5  6  7  8]
 [13  9 11 12]]

  Matrix   B: 
[[3 2 1 5]
 [5 6 7 4]]

 B-A 
[[2 4 6 3]
 [8 3 4 8]]


### Multiply a Matrix by a Scalar

In [30]:
A = np.array([[1,2,3],[4,5,6]])

print('Matrix A:')
print(A)

print('\nMatrix A multiplied by scalar:')
print(3*A)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix A multiplied by scalar:
[[ 3  6  9]
 [12 15 18]]


### Matrix Multiplication

In [31]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,10],[8,11],[9,12]])

print('Matrix A (2x3):')
print(A)
print('Matrix B (3x2):')
print(B)    

print('\n Matrix multiplication AB (2x2):')
print(np.matmul(A,B))

print('\n Matrix multiplication BA (3x3):')
print(np.matmul(B,A))

print('\n-------------------------\n')
print('Matrix multiplication AB (2x2) using @ operator:')
print(A@B)

print('Matrix multiplication BA (3x3) using @ operator:')
print(B@A)

print('\n It also shows that AB != BA')

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]
Matrix B (3x2):
[[ 7 10]
 [ 8 11]
 [ 9 12]]

 Matrix multiplication AB (2x2):
[[ 50  68]
 [122 167]]

 Matrix multiplication BA (3x3):
[[47 64 81]
 [52 71 90]
 [57 78 99]]

-------------------------

Matrix multiplication AB (2x2) using @ operator:
[[ 50  68]
 [122 167]]
Matrix multiplication BA (3x3) using @ operator:
[[47 64 81]
 [52 71 90]
 [57 78 99]]

 It also shows that AB != BA


### Division

In [32]:
A = np.array([[10,12,14,16],[5,6,9,8]])
B = np.array([[2,3,7,8],[1,2,3,4]])
print("   MAtrix  A: ")
print(A)

print("\n  Matrix   B: ")
print(B)

print("\n A/B ")
sum = A//B
print(sum)

   MAtrix  A: 
[[10 12 14 16]
 [ 5  6  9  8]]

  Matrix   B: 
[[2 3 7 8]
 [1 2 3 4]]

 A/B 
[[5 4 2 2]
 [5 3 3 2]]


### Determinant
         _       _
        |  5   2  |
    A = |_ 3   4 _|
    
    Determinant of A = det(A ) = (5 x 4 ) - (2x3) = 20 - 6 = 14

In [33]:
A = np.array([[5,2],[3,4]])
print("matrix A:")
print(A)

det = np.linalg.det(A)
print("determinant: ", round(det))

matrix A:
[[5 2]
 [3 4]]
determinant:  14.0


In [34]:
# higher order matrices
R = np.array([[9,7,6,5,33,2],[0,1,3,0,8,7],[1,0,2,3,5,4],[3,2,0,1,3,7],[1,9,2,0,1,3],[1,2,3,4,5,6]])
print(" Matrix: ")
print(R)
print("\n Shape: ",np.shape(R))
det_R = np.linalg.det(R)
print("\n Determinant is :",round(det_R))

 Matrix: 
[[ 9  7  6  5 33  2]
 [ 0  1  3  0  8  7]
 [ 1  0  2  3  5  4]
 [ 3  2  0  1  3  7]
 [ 1  9  2  0  1  3]
 [ 1  2  3  4  5  6]]

 Shape:  (6, 6)

 Determinant is : 132.0


### Minors 

#### Minor of Element of a Matrix:
        
        if Aij is an entry of square matrix "A", then its Minor ( Mij) is obtained by taking the determinant of the matrix    by ignoring the row and column in which that element lies.

    

In [35]:
# minor of single element of a matrix
def minor_of_element(A,i,j):
    sub_A = np.delete(A,i-1,0)     # Delete i-th row
 #   print("after deleting row \n", sub_A)
    sub_A = np.delete(sub_A,j-1,1) # Delete j-th column
 #   print("after deleting column \n",sub_A)
    M_ij = np.linalg.det(sub_A)    # Minor of the element at ith row and jth column
    return np.around(M_ij,decimals=3)  # Rounding the value

In [36]:
P = np.array([[1,3,5],[2,0,4],[4,2,7]])
print('Matrix P:')
print(P)
print('Minor of the element " ',P[0][1]  ,'" at 1st row and 1st column:')
print(minor_of_element(P,1,2))

Matrix P:
[[1 3 5]
 [2 0 4]
 [4 2 7]]
Minor of the element "  3 " at 1st row and 1st column:
-2.0


#### Minor matrix

In [37]:
# minor matrix
def minor_matrix(A):
    m = np.shape(A)[0]    # Order of the matrix
    M_A = np.zeros([m,m])   # Initializing the minor matrix with zeros
    for i in range(1,m+1):
        for j in range(1,m+1):
            M_A[i-1,j-1] = minor_of_element(A,i,j)
    return M_A

In [38]:
P = np.array([[1,3,5],[2,0,4],[4,2,7]])
print('Matrix P:')
print(P)
print('\n Minor Matrix:\n')
print(minor_matrix(P))

Matrix P:
[[1 3 5]
 [2 0 4]
 [4 2 7]]

 Minor Matrix:

[[ -8.  -2.   4.]
 [ 11. -13. -10.]
 [ 12.  -6.  -6.]]


### CoFactors of a matrix
   
CoFactor:
        
        If Aij is any element of a matrix, then its cofactor is given by:
                Cij = (-1)^(i+j) . Mij
    

In [39]:
def cofactor_matrix(A):
    m = np.shape(A)[0]   # Order of the matrix
    C_A = np.zeros([m,m])   # Initializing the cofactor matrix with zeros
    for i in range(1,m+1):
        for j in range(1,m+1):
            C_A[i-1,j-1] = pow(-1,i+j)*minor_of_element(A,i,j)
    return C_A



In [40]:
P = np.array([[1,3,5],[2,0,4],[4,2,7]])
print('Matrix P:')
print(P)
print('\n Cofactor Matrix:\n')
print(cofactor_matrix(P))

Matrix P:
[[1 3 5]
 [2 0 4]
 [4 2 7]]

 Cofactor Matrix:

[[ -8.   2.   4.]
 [-11. -13.  10.]
 [ 12.   6.  -6.]]


### Checking for the Singularity of a Matrix Using Python

    Matrix "A" is Singular, If det(A) = 0
    Matrix "A" is Non-Singular, If det(A) != 0

In [41]:
def check_singular(A):
    if (np.isclose(np.linalg.det(A),0)):
        result = "Matrix is singular because determinant is "+str(round(np.linalg.det(A)))
    
    else:
        result = "Matrix is non - singular because determinant is "+str(round(np.linalg.det(A)))
     
    return result

In [42]:
P = np.array([[1,3,5],[2,0,4],[4,2,7]])
S = np.array([[8,-6,2],[-6,7,-4],[2,-4,3]])

print('Matrix P:')
print(P)
print('Is Matrix P singular:')
print(check_singular(P))
print('\n------------------------------\n')

print('Matrix S:')
print(S)
print('Is Matrix S singular:')
print(check_singular(S))

Matrix P:
[[1 3 5]
 [2 0 4]
 [4 2 7]]
Is Matrix P singular:
Matrix is non - singular because determinant is 18.0

------------------------------

Matrix S:
[[ 8 -6  2]
 [-6  7 -4]
 [ 2 -4  3]]
Is Matrix S singular:
Matrix is singular because determinant is 0.0


### Properties of the Determinants Using Python
We will validate three properties of the determinants with examples to consolidate our understanding.



###### 1. The determinant of a matrix and the transpose of a matrix are equal.
        |A| = | A.T |

In [43]:
P = np.array([[1,3,5],[2,0,4],[4,2,7]])
print(' Matrix P:')
print(P)

print('\n Transpose of Matrix P:')
print(P.T)

print('\n Determinant of Matrix P:')
print(np.around(np.linalg.det(P), decimals=4))   # Rounding the value

print('\n Determinant of the Transpose of Matrix P:')
print(np.around(np.linalg.det(P.T), decimals=4))   # Rounding the value



 Matrix P:
[[1 3 5]
 [2 0 4]
 [4 2 7]]

 Transpose of Matrix P:
[[1 2 4]
 [3 0 2]
 [5 4 7]]

 Determinant of Matrix P:
18.0

 Determinant of the Transpose of Matrix P:
18.0


###### 2. If we interchange two rows or two columns then:
            |B| = -|A|

In [44]:
A = np.array([[3,5,1],[2,4,9],[7,1,6]])
A_dash = np.array([[2,4,9],[3,5,1],[7,1,6]])

print('Matrix A:')
print(A)
print('Determinant of Matrix A:')
print(np.around(np.linalg.det(A), decimals=4))   # Rounding the value
print('\n------------------------------\n')

print("Matrix A':")
print(A_dash)
print("Determinant of Matrix A':")
print(np.around(np.linalg.det(A_dash),      decimals=4))   # Rounding the value


Matrix A:
[[3 5 1]
 [2 4 9]
 [7 1 6]]
Determinant of Matrix A:
274.0

------------------------------

Matrix A':
[[2 4 9]
 [3 5 1]
 [7 1 6]]
Determinant of Matrix A':
-274.0


##### 3. If any two rows or columns of a matrix are the identical, then the determinant is zero.


In [45]:
A = np.array([[2,3,5],[2,3,5],[7,11,13]])

print("Matrix A:")
print(A)
print("Determinant of Matrix A:")
print(np.around(np.linalg.det(A), decimals=4))   # Rounding the value

Matrix A:
[[ 2  3  5]
 [ 2  3  5]
 [ 7 11 13]]
Determinant of Matrix A:
0.0


### Inverse of a matrix

In [46]:
from scipy import linalg

A = np.array([[2,4],[3,5]])

print(" Matrix A:")
print(A)
print("\n Inverse of Matrix A:")
print(linalg.inv(A))               #Inverse

 Matrix A:
[[2 4]
 [3 5]]

 Inverse of Matrix A:
[[-2.5  2. ]
 [ 1.5 -1. ]]


In [47]:
# for verification
# ( A ).(inverse of A) = indentity matrix

print(np.around(A @ linalg.inv(A), decimals=4))

[[1. 0.]
 [0. 1.]]


### Echelon Form

Matrix will be in Echelon form if the following Two conditions are satisfied:

     i. The first non-zero element in each row  lies to the right of the first non-zero element in its preceding rows.
    ii. If there is any zero row in a matrix, then it will lie below the non-zero rows.

In [48]:
from sympy import *
A=np.mat([[1,5,1],[2,1,1],[3,6,2]])
print(" Matrix A: ")
print(A)
print("\n Echelon Form")
Matrix(A).echelon_form()


 Matrix A: 
[[1 5 1]
 [2 1 1]
 [3 6 2]]

 Echelon Form


Matrix([
[1,  5,  1],
[0, -9, -1],
[0,  0,  0]])

### Rank

In [49]:
print("Rank : " ,np.linalg.matrix_rank(A))

Rank :  2


### Reduced Echelon Form

In [50]:
A=np.mat([[4,2,6],[2,3,4],[4,5,8]])
print(" Matrix A: ")
print(A)
print("\n Reduced Echelon Form")
Matrix(A).rref()

 Matrix A: 
[[4 2 6]
 [2 3 4]
 [4 5 8]]

 Reduced Echelon Form


(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

## Solutions of System of Linear Equations

##### Linear Equation: 

    Algebraic equation in which the higher power of all variables is 1.

##### System of Linear Equations:

    The coolection of linear equations having the same solution of linear equation

### *Gauss Elimination Method

In [51]:
# Importing NumPy Library
import numpy as np
import sys

# Reading number of unknowns
n = int(input('Enter number of unknowns: '))

# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Reading augmented matrix coefficients
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

print("\n")
print(a,"\n")
# Applying Gauss Elimination
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
        
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

# Back Substitution
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i+1,x[i]), end = '\t')

Enter number of unknowns: 3
Enter Augmented Matrix Coefficients:
a[0][0]=1
a[0][1]=3
a[0][2]=-2
a[0][3]=5
a[1][0]=3
a[1][1]=5
a[1][2]=7
a[1][3]=8
a[2][0]=2
a[2][1]=4
a[2][2]=5
a[2][3]=7


[[ 1.  3. -2.  5.]
 [ 3.  5.  7.  8.]
 [ 2.  4.  5.  7.]] 


Required solution is: 
X1 = -1.80	X2 = 2.40	X3 = 0.20	

# *Gauss Jordan Method

In [52]:
# Importing NumPy Library
import numpy as np
import sys

# Reading number of unknowns
n = int(input('Enter number of unknowns: '))

# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Reading augmented matrix coefficients
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

print("\n")
print(a,"\n")
# Applying Gauss Jordan Elimination
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]

            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]

# Obtaining Solution

for i in range(n):
    x[i] = a[i][n]/a[i][i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i+1,x[i]), end = '\t')
    

Enter number of unknowns: 3
Enter Augmented Matrix Coefficients:
a[0][0]=2
a[0][1]=3
a[0][2]=4
a[0][3]=5
a[1][0]=6
a[1][1]=4
a[1][2]=2
a[1][3]=1
a[2][0]=8
a[2][1]=7
a[2][2]=9
a[2][3]=5


[[2. 3. 4. 5.]
 [6. 4. 2. 1.]
 [8. 7. 9. 5.]] 


Required solution is: 
X1 = -2.03	X2 = 3.47	X3 = -0.33	

### Jacobi Method

In [70]:
# Defining equations to be solved
# in diagonally dominant form
#20x + y - 2z = 17
#3x + 20y -z = -18
#2x - 3y + 20z = 25

f1 = lambda x,y,z: (17-y+2*z)/20
f2 = lambda x,y,z: (-18-3*x+z)/20
f3 = lambda x,y,z: (25-2*x+3*y)/20

#x = (17-y+2z)/20
#y = (-18-3x+z)/20
#z = (25-2x+3y)/20

# Initial setup
x0 = 0
y0 = 0
z0 = 0
count = 1

# Reading tolerable error
e = float(input('Enter tolerable error: '))

# Implementation of Jacobi Iteration
print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x0,y0,z0)
    z1 = f3(x0,y0,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);
    
    count += 1
    x0 = x1
    y0 = y1
    z0 = z1
    
    condition = e1>e and e2>e and e3>e

print('\nSolution: x=%0.3f, y=%0.3f and z = %0.3f\n'% (x1,y1,z1))

Enter tolerable error: 0.0001

Count	x	y	z

1	0.8500	-0.9000	1.2500

2	1.0200	-0.9650	1.0300

3	1.0012	-1.0015	1.0032

4	1.0004	-1.0000	0.9996

5	1.0000	-1.0001	1.0000


Solution: x=1.000, y=-1.000 and z = 1.000



### Gauss Seidel Iteration

In [69]:
# Gauss Seidel Iteration

# Defining equations to be solved
# in diagonally dominant form
f1 = lambda x,y,z: (17-y+2*z)/20
f2 = lambda x,y,z: (-18-3*x+z)/20
f3 = lambda x,y,z: (25-2*x+3*y)/20

# Initial setup
x0 = 0
y0 = 0
z0 = 0
count = 1

# Reading tolerable error
e = float(input('Enter tolerable error: '))

# Implementation of Gauss Seidel Iteration
print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x1,y0,z0)
    z1 = f3(x1,y1,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);
    
    count += 1
    x0 = x1
    y0 = y1
    z0 = z1
    
    condition = e1>e and e2>e and e3>e

print('\nSolution: x=%0.3f, y=%0.3f and z = %0.3f\n'% (x1,y1,z1))

Enter tolerable error: 0.0001

Count	x	y	z

1	0.8500	-1.0275	1.0109

2	1.0025	-0.9998	0.9998

3	1.0000	-1.0000	1.0000

4	1.0000	-1.0000	1.0000


Solution: x=1.000, y=-1.000 and z = 1.000

